/*  docWX: A minimal, performant book-keeping, authoring and documentation tool.
Copyright (C) 2026  Xe64

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.*/

use phf::phf_map;

pub const fn build_tables() -> phf::Map<&'static str, &'static str> {
    phf_map! {
         "requirements.txt" => "#&",
         "pip.conf" => "#&",
         "meson_options.txt" => "#&",
         "meson.build" => "#&",
         "WORKSPACE" => "#&",
         "Makefile" => "#&",
         "GNUMakefile" => "#&",
         "Dockerfile" => "#&",
         "CMakeLists.txt" => "#&",
         "BUILD" => "#&",
         "BSDmakefile" => "#&",
         ".zshrc" => "#&",
         ".zshenv" => "#&",
         ".zsh" => "#&",
         ".zprofile" => "#&",
         ".zig" => "//&",
         ".yml" => "#&",
         ".yaml" => "#&",
         ".v" => "//&",
         ".tsx" => "//&",
         ".ts" => "//&",
         ".toml" => "#&",
         ".tcl" => "#&",
         ".swift" => "//&",
         ".ss" => ";;&",
         ".sh" => "#&",
         ".scm" => ";;&",
         ".scala" => "//&",
         ".s" => ";&",
         ".rs" => "//&",
         ".rkt" => ";;&",
         ".rei" => "//&",
         ".re" => "//&",
         ".rb" => "#&",
         ".py" => "#&",
         ".profile" => "#&",
         ".pm" => "#&",
         ".pl" => "#&",
         ".nim" => "#&",
         ".mm" => "//&",
         ".mli" => "*&",
         ".ml" => "*&",
         ".mk" => "#&",
         ".mjs" => "//&",
         ".m" => "//&",
         ".lisp" => ";;&",
         ".kts" => "//&",
         ".kt" => "//&",
         ".jsx" => "//&",
         ".js" => "//&",
         ".jl" => "#&",
         ".java" => "//&",
         ".jai" => "//&",
         ".ini" => "#&",
         ".hxx" => "//&",
         ".hs" => "--&",
         ".hpp" => "//&",
         ".hh" => "//&",
         ".h" => "//&",
         ".go" => "//&",
         ".gitmodules" => "#&",
         ".gitlab-ci.yml" => "#&",
         ".gitlab-ci.yaml" => "#&",
         ".gitignore" => "#&",
         ".gitattributes" => "#&",
         ".fsi" => "//&",
         ".fs" => "//&",
         ".fish" => "#&",
         ".env" => "#&",
         ".elm" => "--&",
         ".el" => ";;&",
         ".editorconfig" => "#&",
         ".d" => "//&",
         ".cxx" => "//&",
         ".cuh" => "//&",
         ".cu" => "//&",
         ".cs" => "//&",
         ".cpp" => "//&",
         ".conf" => "#&",
         ".cmake" => "#&",
         ".cljs" => ";;&",
         ".cljc" => ";;&",
         ".clj" => ";;&",
         ".cl" => ";;&",
         ".cjs" => "//&",
         ".cc" => "//&",
         ".c" => "//&",
         ".bzl" => "#&",
         ".bazel" => "#&",
         ".bashrc" => "#&",
         ".bash_profile" => "#&",
         ".bash" => "#&",
         ".awk" => "#&",
         ".asm" => ";&",
    }
}
